name: Product tests
description: "Run NHS Notify product tests"

runs:
  using: "composite"

  steps:
    - name: "Repo setup"
      shell: bash
      run: |
        npm ci
    - name: Run test - ${{ inputs.testType }}
      shell: bash
      run: |
        make test-product
    - name: Archive product test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Product test report
        path: "tests/test-team/playwright-report"
