name: Product tests
description: 'Run NHS Notify product tests'

inputs:
  targetEnvironment:
    description: Name of the environment under test
    required: true
    default: main
  github_token:
    description: GitHub access token
    required: true
  github_run_id:
    description: GitHub Run ID the action is being run from
    required: true
  github_repository:
    description: GitHub Repository the action is being run from (owner/repo-name format)
    required: true

runs:
  using: 'composite'

  steps:
    - name: 'Repo setup'
      shell: bash
      run: |
        npm ci

    - name: Download setup JSON artifact (auth service)
      env:
        GH_TOKEN: ${{ inputs.github_token }}
      run: |
        ARTIFACT_NAME="auth-state"
        DEST_PATH="./tests/test-team/lifecycle/auth"
        echo "Downloading artifact '$ARTIFACT_NAME' to $DEST_PATH ..."
        gh run download "${{ inputs.github_run_id }}" --repo "${{ inputs.github_repository }}" --name "$ARTIFACT_NAME" --dir "$DEST_PATH"
      shell: bash

    - name: Run product tests
      shell: bash
      env:
        TARGET_ENVIRONMENT: ${{ inputs.targetEnvironment }}
      run: |
        make test-product

    - name: Archive product test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Product test report
        path: 'tests/test-team/playwright-report'
