name: Product tests
description: "Run NHS Notify product tests"

inputs:
  targetComponent:
    description: Name of the component under test
    default: app

runs:
  using: "composite"

  steps:
    # - name: Fetch terraform output
    #   uses: actions/download-artifact@v4
    #   with:
    #     name: terraform-output-${{ inputs.targetComponent }}
    - name: "Repo setup"
      shell: bash
      run: |
        npm ci
    # - name: Generate outputs file
    #   shell: bash
    #   run: |
    #     root_dir=${GITHUB_WORKSPACE}
    #     mv ./terraform_output.json ./sandbox_tf_outputs.json
    #     npm run generate-outputs sandbox-output
    - name: Run test - ${{ inputs.testType }}
      shell: bash
      run: |
        make test-product
    - name: Archive product test results
      uses: actions/upload-artifact@v4
      with:
        name: Product test report
        path: "tests/test-team/playwright-report"
