name: Security scan
description: "Run security scan"

inputs:
  webGatewayEnvironment:
    description: Subdomain indicating a static web gateway
    required: false
    default: main

  iamEnvironment:
    description: Static IAM environment connected to the web gateway being tested
    required: false
    default: main

  templateManagementBranch:
    description: Branch level template management environment. If empty, main branch is used
    required: false
    default: ""

runs:
  using: "composite"

  steps:
    - name: "Repo setup"
      shell: bash
      run: |
        npm ci
    - name: Install Playwright Browsers
      shell: bash
      run: npx -w=tests/security playwright install --with-deps --only-shell

    - name: Run test - security scan
      shell: bash
      run: |
        ./tests/security/run.sh \
          "${{ inputs.webGatewayEnvironment }}" \
          "${{ inputs.iamEnvironment }}" \
          "${{ inputs.templateManagementBranch }}"

    - name: Archive security test results
      uses: actions/upload-artifact@v4
      with:
        name: Security test report
        path: "tests/security/report/zap-out-*.html"

