name: Security scan
description: "Run security scan"

inputs:
  webGatewayEnvironment:
    description: "Web gateway subdomain to test"
    required: false
    default: main
  iamEnvironment:
    description: "Static IAM environment in which a test user will be created"
    required: false
    default: main
  templateManagementBranch:
    description: "Optional branch level web-template-management frontend to test. Empty default implies main"
    required: false
    default: ""

runs:
  using: "composite"

  steps:
    - name: "Repo setup"
      shell: bash
      run: |
        npm ci
    - name: Install Playwright Browsers
      shell: bash
      run: npx -w=tests/security playwright install --with-deps

    - name: Run test - security scan
      id: test
      shell: bash
      run: |
        ./tests/security/run.sh \
          "${{ inputs.webGatewayEnvironment  }}" \
          "${{ inputs.iamEnvironment  }}" \
          "${{ inputs.templateManagementBranch  }}" \
          || echo "exit_code=$?" >> $GITHUB_OUTPUT

    - name: Archive security test results
      uses: actions/upload-artifact@v4
      with:
        name: Security test report
        path: "tests/security/zap-out-*.html"

    - name: Fail workflow on test failure
      shell: bash
      if: steps.test.outputs.exit_code != 0
      run: |
        echo "Security tests failed with exit code ${{ steps.test.outputs.exit_code }}"
        exit 1
