name: Security scan
description: "Run security scan"

runs:
  using: "composite"

  steps:
    - name: "Repo setup"
      shell: bash
      run: |
        npm ci
    - name: Install Playwright Browsers
      shell: bash
      run: npx -w=tests/security playwright install --with-deps

    - name: Run test - security scan
      shell: bash
      run: ./tests/security/run.sh

    - name: Archive security test results
      uses: actions/upload-artifact@v4
      with:
        name: Security test report
        path: "tests/security/zap-out-*.html"

