#!/usr/bin/env tsx
/**
 * Product Test Scaffolder
 * Generates a new Playwright product test file following standards in tests/test-team/standards/TEST_STANDARDS.md.
 *
 * Usage:
 *   npm run generate:product-test -- --area template-mgmt --action create-letter-template --outcome "upload and verify letter template proof" --pageObject TemplateMgmtLetterPage
 *
 * Flags:
 *   --area <string>            Required: logical area (e.g. template-mgmt)
 *   --action <string>          Required: action verb phrase (e.g. create-letter-template)
 *   --outcome <string>         Optional: outcome phrase for test title after should (defaults to action)
 *   --pageObject <string>      Optional: page object class to import (default inferred for known areas)
 *   --force                    Optional: overwrite existing file
 *   --dryRun                   Show intended path without writing file
 *
 * Output Path Pattern:
 *   tests/test-team/<area>-e2e-tests/<area>-<action>-e2e.ts
 */

import { mkdirSync, existsSync, writeFileSync } from 'fs';
import { join } from 'path';

interface Args { [k: string]: string | boolean | undefined; }

function parseArgs(): Args {
  const raw = process.argv.slice(2);
  const args: Args = {};
  for (let i = 0; i < raw.length; i++) {
    const token = raw[i];
    if (!token.startsWith('--')) continue;
    const eqIndex = token.indexOf('=');
    if (eqIndex > -1) {
      const key = token.substring(2, eqIndex);
      const value = token.substring(eqIndex + 1);
      args[key] = value;
    } else {
      const key = token.substring(2);
      const next = raw[i + 1];
      if (next && !next.startsWith('--')) {
        args[key] = next;
        i++; // consume value token
      } else {
        args[key] = true; // boolean flag
      }
    }
  }
  return args;
}

function slugify(input: unknown): string {
  if (typeof input !== 'string') return '';
  return input.trim().toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
}

function inferPageObject(area: string): string | null {
  switch (area) {
    case 'template-mgmt':
      return 'TemplateMgmtLetterPage';
    default:
      return null;
  }
}

function buildBoilerplate(opts: { area: string; action: string; outcome: string; pageObject?: string | null; }): string {
  const { area, action, outcome, pageObject } = opts;
  const describeName = `${area}: ${action}`;
  const testTitle = `should ${outcome}`;
  const importPageObject = pageObject ? `import { ${pageObject} } from '../pages/${area}-letter-page'; // adjust import if different page file\n` : `// TODO: provide page object import and implementation\n`;
  const poInstantiation = pageObject ? `const pageObj = new ${pageObject}(page);\n    await pageObj.navigateTo(process.env.TARGET_ENVIRONMENT!);` : `// TODO: instantiate page object and navigate\n    // await pageObj.navigateTo(process.env.TARGET_ENVIRONMENT!);`;

  return `import { test, expect } from '@playwright/test';\n${importPageObject}import { loginWithCis2 } from '../functions/login';\n\n// Generated by scripts/generate-product-test.ts on ${new Date().toISOString()}\n// Follow standards: tests/test-team/standards/TEST_STANDARDS.md\n\ntest.describe('${describeName}', () => {\n  test('${testTitle}', async ({ page }) => {\n    ${poInstantiation}\n    await loginWithCis2(pageObj ?? page, 'Scenario: ${action}');\n\n    // IMPLEMENT: interactions using page object methods\n    // Example: await pageObj.uploadLetterTemplate('My Test Template');\n    // Example: await pageObj.waitForProofRequest();\n\n    // EXPECTATION: replace placeholder with a resilient role/testid selector\n    // allowable direct locator (remove if replaced)\n    // await expect(page.getByRole('heading', { name: /Request a proof/i })).toBeVisible();\n    await expect(page).toBeTruthy(); // placeholder assertion to keep linter happy; replace\n  });\n});\n`;
}

function main() {
  const args = parseArgs();
  const area = typeof args.area === 'string' ? args.area : '';
  const action = typeof args.action === 'string' ? args.action : '';
  if (!area || !action) {
    console.error('Error: --area and --action are required.');
    process.exit(1);
  }
  const outcome = typeof args.outcome === 'string' ? args.outcome : action;
  const force = !!args.force;
  const dryRun = !!args.dryRun;
  const pageObject = typeof args.pageObject === 'string' ? args.pageObject : inferPageObject(area);

  const areaSlug = slugify(area);
  const actionSlug = slugify(action);
  const testsDir = join('tests', 'test-team', `${areaSlug}-e2e-tests`);
  const fileName = `${areaSlug}-${actionSlug}-e2e.ts`;
  const filePath = join(testsDir, fileName);

  if (dryRun) {
    console.log(`Dry run: would create ${filePath}`);
    process.exit(0);
  }

  if (existsSync(filePath) && !force) {
    console.error(`File already exists: ${filePath} (use --force to overwrite)`);
    process.exit(1);
  }

  if (!existsSync(testsDir)) {
    mkdirSync(testsDir, { recursive: true });
  }

  const content = buildBoilerplate({ area: areaSlug, action: actionSlug, outcome: outcome, pageObject });
  writeFileSync(filePath, content, { encoding: 'utf8' });
  console.log(`Created test file: ${filePath}`);
}

main();
