name: Product tests cleanup
description: "Run product tests cleanup"

inputs:
  targetEnvironment:
    description: Name of the environment under test
    required: true
    default: main
  testUsers:
    description: JSON Array<string> of test user IDs (subject)
    required: true

runs:
  using: "composite"

  steps:
    - name: "Repo setup"
      shell: bash
      run: |
        npm ci
    - name: Cleanup test data
      shell: bash
      env:
        TARGET_ENVIRONMENT: ${{ inputs.targetEnvironment }}
        TEST_USERS: ${{ inputs.testUsers }}
      run: |
        make test-data-cleanup
