name: Call Notify Internal Infrastructure Workflow

on:
  workflow_call:
    inputs:
      jobName:
        type: string
        description: The name of the job triggering the remote workflow
        required: true
      infraRepoName:
        type: string
        description: Repository (this one) in the NHSDigital Github Org to deploy from
        required: true
      releaseVersion:
        type: string
        description: The Github release version, commit, or tag.
        default: main
      targetWorkflow:
        type: string
        description: The name of the github workflow to call.
        required: true
      targetEnvironment:
        type: string
        description: The environment to test
        default: main
      assumeRoleAccount:
        type: string
        description: The account in which the test runner will assume its role
        default: ""

concurrency:
  group: ${{ inputs.targetEnvironment }}-${{ inputs.releaseVersion }}-${{ inputs.targetWorkflow }}-${{ inputs.jobName }}

jobs:
  trigger:
    name: ${{ inputs.jobName }}
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Trigger nhs-notify-internal workflow
        shell: bash
        run: |
          DISPATCH_EVENT=$(jq -ncM \
            --arg infraRepoName "${{ inputs.infraRepoName }}" \
            --arg releaseVersion "${{ inputs.releaseVersion }}" \
            --arg targetEnvironment "${{ inputs.targetEnvironment }}" \
            --arg assumeRoleAccount "${{ inputs.assumeRoleAccount }}" \
            '{
              "ref": "feature/CCM-10132_test-data-cleanup",
              "inputs": (
                (if $assumeRoleAccount != "" then { "assumeRoleAccount": $assumeRoleAccount } else {} end) +
                {
                  "releaseVersion": $releaseVersion,
                  "targetEnvironment": $targetEnvironment,
                  "infraRepoName": $infraRepoName
                }
              )
            }')

          # Trigger The workflow
          curl -L \
            --fail \
            --silent \
            -w "HTTP status code: %{http_code}\n" \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.ACTION_TRIGGER_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/NHSDigital/nhs-notify-internal/actions/workflows/${{ inputs.targetWorkflow }}/dispatches" \
            -d "${DISPATCH_EVENT}"

          echo "Workflow triggered. Waiting for the workflow to complete.."

      - name: Wait for nhs-notify-internal workflow to start
        shell: bash
        timeout-minutes: 15
        run: |
          # Poll GitHub API to check the workflow status
          workflow_run_url=""
          while true; do
            in_progress=$(
              curl -s \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.ACTION_TRIGGER_PAT }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                "https://api.github.com/repos/NHSDigital/nhs-notify-internal/actions/runs?event=workflow_dispatch&status=in_progress"
            )
            workflow_run_url=$(
              echo $in_progress \
              | jq -r --arg jobName "${{ inputs.jobName }}" \
                  '.workflow_runs[]
                    | select(.name
                    | contains("'${{ inputs.targetEnvironment }}'") and
                      contains($jobName) and
                      contains("${{ inputs.infraRepoName }}"))
                    | .url'
            )
            if [[ -n "$workflow_run_url" && "$workflow_run_url" != null ]]; then
              ui_url=${workflow_run_url/api./}
              ui_url=${ui_url/\/repos/}
              echo "Found workflow run url: $ui_url"
              echo "workflow_run_url=$workflow_run_url" >> $GITHUB_ENV
              break
            fi

            echo "Waiting for workflow to start..."
            sleep 15
          done

          echo "Pipeline started successfully"

      - name: Wait for nhs-notify-internal to complete
        shell: bash
        run: |
          # Wait for workflow completion
          while true; do
            sleep 10
            response=$(curl -s -L \
              -H "Authorization: Bearer ${{ secrets.ACTION_TRIGGER_PAT }}" \
              -H "Accept: application/vnd.github+json" \
              $workflow_run_url)

            status=$(echo "$response" | jq -r '.status')
            conclusion=$(echo "$response" | jq -r '.conclusion')

            if [ "$status" == "completed" ]; then
              if [ "$conclusion" == "success" ]; then
                echo "Workflow completed successfully."
                exit 0
              else
                echo "Workflow failed with conclusion: $conclusion"
                exit 1
              fi
            fi

            echo "Workflow still running..."
            sleep 20
          done
