name: Product level Playwright tests

on:
  workflow_dispatch:
    inputs:
      targetEnvironment:
        type: string
        description: "Web gateway environmnet to test"
        required: false
        default: main
  schedule:
    - cron: "0 9 * * *"

jobs:
  product-tests:
    name: Product Test

    permissions:
      id-token: write
      contents: read

    uses: ./.github/workflows/dispatch_internal_repo_workflow.yaml
    secrets: inherit
    with:
      jobName: Product Tests
      infraRepoName: nhs-notify-system-tests
      releaseVersion: ${{ github.head_ref || github.ref_name }}
      targetWorkflow: dispatch-product-tests-static-env.yaml
      targetEnvironment: ${{ inputs.targetEnvironment || 'main'  }}
