name: Security tests

on:
  push:
  schedule:
    - cron: "0 9 * * *"

jobs:
  security-test:
    name: Security Test

    permissions:
      id-token: write
      contents: read

    uses: ./.github/workflows/dispatch_internal_repo_workflow.yaml
    secrets: inherit
    with:
      jobName: Security Tests
      infraRepoName: nhs-notify-system-tests
      releaseVersion: ${{ github.head_ref || github.ref_name }}
      targetWorkflow: dispatch-security-tests-static-env.yaml
      targetEnvironment: main
      assumeRoleAccount: 975050048865 # iam-dev
