name: Security scan

on:
  push:
  workflow_dispatch:

jobs:
  security-test:
    name: Security Test

    permissions:
      id-token: write
      contents: read

    uses: ./.github/workflows/dispatch_internal_repo_workflow.yaml
    secrets: inherit
    with:
      jobName: Security test
      infraRepoName: nhs-notify-system-tests
      releaseVersion: ${{ github.head_ref || github.ref_name }}
      targetWorkflow: dispatch-security-tests-static.yaml
      targetEnvironment: main
